name: strong_buddies_connect
description: A new Flutter project.

version: 1.6.12

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.1.1
  flutter_facebook_login: ^3.0.0
  rxdart: ^0.23.1
  provider: ^4.0.4
  validate: ^1.7.0
  image_picker: ^0.6.3+1
  multi_image_picker: ^4.6.1
  cloud_firestore: ^0.13.2+1
  firebase_storage: ^3.1.1
  cupertino_icons: ^0.1.2
  bloc: ^3.0.0
  cached_network_image: 2.0.0-rc.1
  flutter_bloc: ^3.2.0
  equatable: ^1.1.0
  uuid: ^2.0.4
  progress_dialog: ^1.2.1
  geolocator: ^5.2.1
  location: ^2.4.0
  photo_view: ^0.5.0
  flutter_local_notifications: ^0.8.4
  fluttertoast: ^3.1.3
  intl: ^0.15.7
  firebase_messaging: ^5.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/background-login.jpg
    - assets/images/logo.png
    - assets/images/demo_image.jpg

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 900
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 600
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
