name: strong_buddies_connect
description: A new Flutter project.

version: 0.2.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  geoflutterfire: ^2.1.0
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.0
  google_sign_in: ^4.1.1
  flutter_facebook_login: ^3.0.0
  rxdart: ^0.23.1
  provider: ^4.1.3
  validate: ^1.7.0
  image_picker: ^0.6.3+1
  multi_image_picker: ^4.6.1
  cloud_firestore: ^0.13.2+1
  firebase_storage: ^3.1.1
  cupertino_icons: ^0.1.2
  bloc: ^4.0.0
  cached_network_image: 2.0.0-rc.1
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  uuid: ^2.0.4
  progress_dialog: ^1.2.1
  geolocator: ^5.2.1
  location: ^2.4.0
  photo_view: ^0.5.0
  flutter_local_notifications: ^0.8.4
  fluttertoast: ^3.1.3
  intl: ^0.15.7
  firebase_messaging: ^6.0.16
  flutter_screenutil: ^1.0.2
  font_awesome_flutter: ^8.8.1
  http: ^0.12.1
  devicelocale: ^0.2.1
  flutter_staggered_grid_view: ^0.3.0
  shimmer: ^1.1.1
  dotted_border: ^1.0.6
  flutter_svg: ^0.19.0
  get: ^3.12.1
  apple_sign_in: ^0.1.0
  carousel_slider: ^3.0.0
  shared_preferences: ^0.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 900
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 600
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
